### PR TITLE
Documented some algorithms 

### PR DESCRIPTION
**Pull request by adrianlshaw**
This small PR introduces some small, consistent descriptions to the various cipher modes.

GMAC is removed because it can't be implemented with the current version of the API.

### CODE REVIEW

**Comment by adrianlshaw** [comment]
Thanks for the review. I've taken your advice. Hope I've been less sloppy this time round.

**Comment by gilles-peskine-arm** [comment]
The build is still failing. You should have permission to view Jenkins results now, by the way.

**Comment by adrianlshaw** [comment]
The CI errors don't look related to any code I've touched. The tips of my fork are up to date and no merge issues detected locally. Any advice?

**Comment by gilles-peskine-arm** [comment]
The diff is fine, but please rebase on top of the branch `psa-api-1.0-beta`, which is the branch that the specification is typeset from. The `development` branch has the latest version of Mbed Crypto, but complies with an older version of the PSA API.

The "Pre Test Checks", "Travis CI" and "Crypto Testing" jobs are expected to pass. "TLS Testing", "pr-head" and "pr-merge" are expected to fail on the API branch.

**Comment by adrianlshaw** [comment]
Closing in favour of #167

**Pull request closed without merging**
