### PR TITLE
Improve how generate_psa_constants handles compatibility aliases

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Improve how generate_psa_constants handles compatibility aliases. Declare a missing alias `PSA_ERROR_TAMPERING_DETECTED`.

Targeting the API branch because that's where the renamings have been happening.

### CODE REVIEW

**Comment by Patater** [comment]
@gilles-peskine-arm Could you please rebase and retarget the development branch if these changes are still relevant and desired?

**Comment by gilles-peskine-arm** [comment]
I'm pretty sure this is still relevant. It got stalled because no one reviewed it. I can pick it up if someone's available to review it.

**Comment by Patater** [comment]
I can review

**Comment by gilles-peskine-arm** [comment]
Rebased to current `development`, since this is where PSA development is happening now.

**Comment by gilles-peskine-arm** [comment]
CI failures were only API changes with deprecated aliases (that's ok) and random DTLS failures (unrelated to this PR). Ok to merge.

**Pull request merged**
