### PR TITLE
Move psa_destroy_key and psa_copy_key to Key Management section

### PR DESCRIPTION
**Pull request by adrianlshaw**
Currently psa_destroy_key and psa_copy_key are in the import/export section but they ought to be in the key management section. So I've simply moved them.

### CODE REVIEW

**Comment by Patater** [comment]
Please rebase on the latest `development` and update this PR to target the `development` branch.

**Comment by Patater** [comment]
The commits look a bit weird. Could you squash them into one commit? I don't believe you are trying to make more than one semantic change, so one commit would be the most readable and reviewable.

**Comment by adrianlshaw** [comment]
Squashed

**Comment by adrianlshaw** [comment]
Rebased 👍

**Comment by Patater** [comment]
CI failure is only files that need updating in Mbed TLS repo concurrently with updating the submodule.

**Pull request merged**
