### PR TITLE
Build: Updated CMAKE_C_FLAGS for IAR

### PR DESCRIPTION
**Pull request by TTornblom**
Updated the IAR specific CMAKE_C_FLAGS settings in CMakeLists.txt to
allow building TF-M (Trusted Firmware) with mbed-crypto as a subproject.

Signed-off-by: TTornblom <thomas.tornblom@iar.com>

### CODE REVIEW

**Comment by TTornblom** [comment]
What are the failing CI tests? I have no access to the details of the failed tests.

**Comment by AndrzejKurek** [comment]
All of the mbed-os tests using K64F with GCC_ARM and IAR are failing. The build is stopped pretty soon, so this is probably not the only error that will be encountered:

> Compile [  7.4%]: attest_crypto_keys.c
> [Error] attest_crypto_keys.c@54,9: duplicate case value
> [Error] attest_crypto_keys.c@57,9: duplicate case value
> [Error] attest_crypto_keys.c@63,9: duplicate case value
> [ERROR] ./mbed-os/components/TARGET_PSA/services/attestation/COMPONENT_PSA_SRV_IMPL/attest_crypto_keys.c: In function 'get_curve':
> ./mbed-os/components/TARGET_PSA/services/attestation/COMPONENT_PSA_SRV_IMPL/attest_crypto_keys.c:54:9: error: duplicate case value
> 54 |         case PSA_ECC_CURVE_SECP384R1:

Please build one of the mbedtls mbed-os examples (like hashing, or benchmark), by running:
`mbed compile -m K64F -t GCC_ARM` or `mbed compile -m K64F -t IAR` in the respective directory.

**Comment by TTornblom** [comment]
I don't see any such issues with either GCC or IAR.
The only issue is that the problam won't link due to a missing main.
I cloned the current version, which includes "mbedcrypto-3.0.0d0".

**Comment by TTornblom** [comment]
@gilles-peskine-arm Please review

**Comment by mpg** [comment]
Everything passed in the CI except some known issues independent from this PR.

**Pull request merged**
