### PR TITLE
Everest integration

### PR DESCRIPTION
**Pull request by yanesca**
This PR is the result of rebasing https://github.com/ARMmbed/mbedtls/pull/2073 on the top of Mbed Crypto development.

This PR has to be merged shortly before https://github.com/ARMmbed/mbedtls/pull/2799 to avoid CI failures.

### CODE REVIEW

**Comment by yanesca** [comment]
On the CI the crypto job is passing, the TLS part of the pr jobs is failing, because the Mbed TLS build scripts seem to pick up the the TLS version of the crypto related headers and not  the crypto version. (Changing this might make sense since crypto does not have the ssl headers anymore, but since the crypto files will be deleted soon, I don't think it is worth the effort.)

**Comment by wintersteiger** [comment]
Just checking: could you give us a rough idea of when this will be merged?

**Comment by yanesca** [comment]
Splitting the repository into Mbed TLS and Mbed Crypto complicated things: This PR is the part of the changes that need to go in Mbed Crypto. There is another part that needs to go in Mbed TLS. Before we could raise this second PR, we need to finish up a splitting related task in Mbed TLS first. Once it is done we will raise the second PR as soon as possible and we can get both of them merged.

**Comment by wintersteiger** [comment]
Sounds good, thanks for the update!

**Comment by achamayou** [comment]
@yanesca any update on this PR? We would be very keen to pick up a release of mbedtls with these changes in for our project.

**Comment by yanesca** [comment]
@achamayou I have rebased this PR, I'll still need to fix the CI failures (if any) and rebase ARMmbed/mbedtls#2073 before we could do the reviews and eventually merge.

**Comment by yanesca** [comment]
CI is only failing, because the PSA API is out of sync between Mbed TLS and Mbed Crypto. This is going to be resolved after merging https://github.com/ARMmbed/mbedtls/pull/2767.

**Comment by achamayou** [comment]
@yanesca thank you for the update, we look forward to using x25519 in mbedtls.

**Comment by yanesca** [comment]
The CI fails only on the `check-names` script when testing with Mbed TLS. The reason is that `MBEDTLS_ECDH_VARIANT_EVEREST_ENABLED` is not present in the Mbed TLS config file yet. This will be fixed when https://github.com/ARMmbed/mbedtls/pull/2799 is merged.

**Comment by yanesca** [comment]
API checking fails on the head, because the development has been updated since the PR had been raised. Merging to development should fix this failure.

**Comment by Patater** [comment]
I see a check-names failure. Anything we can do to avoid it?

```
******************************************************************
* check_names: test/build: declared and exported names 
* Wed Aug 21 14:55:44 UTC 2019
******************************************************************
Analysing source code...
1494 macros
     210 enum-consts
1390 identifiers
413 exported-symbols

Exported symbols declared in header: PASS
Names of actual-macros: PASS
Names of enum-consts: FAIL
#endif
#ifdefined(MBEDTLS_ECDH_VARIANT_EVEREST_ENABLED)
Names of identifiers: PASS
Likely typos: PASS

Overall: FAILED
^^^^check_names: test/build: declared and exported names: tests/scripts/check-names.sh -v -> 1^^^^
```

**Comment by yanesca** [comment]
@Patater That failure is in the TLS tests, and uses TLS's scripts that can't be updated by this PR but are updated by https://github.com/ARMmbed/mbedtls/pull/2799. The failures should go away when 2799 is merged into Mbed TLS. (PR2799 uses this PR as a submodule and the CI is green over there.)

**Comment by Patater** [comment]
@wintersteiger Thanks a lot for your contribution! And especially thanks for your patience working with us to get this in. Much appreciated!

**Comment by wintersteiger** [comment]
Many thanks for getting this merged! It took a little longer than expected, but we're very happy it's now in!

**Pull request merged**
