### PR TITLE
Init function variable to avoid compiler warning

### PR DESCRIPTION
**Pull request by jainvikas8**
Make it more robust.
Issue : https://github.com/ARMmbed/mbedtls/issues/2340

### CODE REVIEW

**Comment by jainvikas8** [comment]
Forced pushed to fix typo commit message.

**Comment by Patater** [comment]
Please copy-paste the compiler warning message into the commit message, including information about the specific toolchain and build options used, as well as explaining why the change is needed.

**Comment by yanesca** [comment]
We couldn't locate the issue in the code, the original reporter didn't come back to Ron and he couldn't give the details and we couldn't reproduce. We are making this change to make the code more robust, avoid introducing an uninitialised read if it is not present and fix it if it is and we missed it.

**Comment by k-stachowiak** [comment]
I can only see two main ways of getting to `return( ret )` in the function:

1. Through:

    if( T == NULL )
    {
        ret = MBEDTLS_ERR_ECP_ALLOC_FAILED;
        goto cleanup;
    }

which sets the `ret` variable.

2. directly, which unconditionally (both in the compile time and in runtime) expands:

    MBEDTLS_MPI_CHK( ecp_mul_comb_after_precomp(
        grp, R, m,
        T, T_size, w, d,
        f_rng, p_rng, rs_ctx ) );

, which, in turn, unconditionally sets the `ret` variable as well.

If we aren't observing the warning anywhere (neither locally nor in the CI or Coverity), I suggest not introducing this change. The proposed initial value doesn't express the actual error, and prevents static analyzers detecting the real lack of assignment should it ever occurs.

**Comment by Patater** [comment]
Closing as not needed and not the right fix. Re-open if you can reproduce the error and know how to fix the real error (as opposed to masking it with blind initialization).

**Comment by k-stachowiak** [comment]
@Patater Please note, that two backports of this PR are still open: ARMmbed/mbedtls#2796 and ARMmbed/mbedtls#2797

**Pull request closed without merging**
